### ISSUE TITLE
"Red Hat Developer" link in header should go to developers.redhat.com

### ISSUE THREAD

**Issue by cbredesen** [Apicurio/apicurio.github.io#27]
JBoss.org is no longer the home of the Red Hat developer experience; we should be using developers.redhat.com. I searched and there are some instances of apicurio on the site but there's no dedicated product page. It's probably fine to just use the home page but I thought I'd file this and let you decide.

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio.github.io/commit/5f8924daf365c39998cca0b470b561c48bc30607
